### ISSUE TITLE
Didn't parse tomorrow 6pm correctly

### ISSUE THREAD

**Issue by fuzzyroddis** [rayzru/event-parser#7]
`Doctor Appointment tomorrow 6pm at Sydney Clinic`

Doctor Appointment  6pm
Sydney Clinic
Sunday, May 15, 2016 12:00:00 AM

Thanks for coding this thought, it looks fantastic!

**Comment by rayzru** [comment]
This bug was fixed in 0.0.22, but demo page was not updated. 
Sorry.
Shold be fixed now.

**Comment by rayzru** [comment]
version updated
